### ISSUE TITLE
To-Do list for Manual

### ISSUE THREAD

**Issue by couet** [root-project/web#23]
- [ ] Make sure we are not losing information from the user’s guide which are not in the reference guide.
- [ ] Scan the most accessed thread in the forum and reflect them in the Manual
- [ ] Add a section explaining what is ROOT 7 (ROOT 7 graphics, RHist, RNtuple etc...) .. why do we have it etc... 
- [x] Add an example showing how to use TTree::ReadFile in the Tree chapter of the manual. It is a very common    request to go simple from an ascii file to a ttree There is many examples in the forum
and the tutorial is basic2.C. We can even show the case where the description of the tree is done on the first file of the data file.
- [x] [This post](https://root-forum.cern.ch/t/fft-on-histogram/44058) refers to the Manual page for FFT but also add a few links. May be the manual FFT page should be updated accordingly ?
